excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BTRaynes.github.io
title: JessieLynneLovesBeauty
tagline: Beauty Therapist &#128156; Makeup &#128153; Skincare &#128156; Nails
description: My awesome new site
paginate: 5